### ISSUE TITLE
Add documentation on setting up docker "properly"

### ISSUE THREAD

**Issue by mattbellis** [cms-opendata-workshop/2020-09-30-cms-open-data-workshop-for-theorists#1]
Need to create more detailed docker instructions. This should probably also go in the Users Guide website. 

* Provide instructions on running docker such that X11 forwarding works (e.g. see ROOT windows come up)

* Provide instructions on how to get the same docker container each time, rather than starting a whole new container. This will allow files you create to stay alive. 

https://stackoverflow.com/questions/28574433/do-docker-containers-retain-file-changes

* Instructions to setup ssh keys to clone Github repos. 

https://help.github.com/en/enterprise/2.15/user/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

**Comment by caredg** [comment]
Goes with #2.  Done, issues moved to its own repo
