### ISSUE TITLE
Wishlist for the AOD2NanoAODOutreachTool enhancement 

### ISSUE THREAD

**Issue by caredg** [cms-opendata-workshop/2020-09-30-cms-open-data-workshop-for-theorists#17]
In this list we can collect the different pieces of information that we need to add to the HTT nanoAOD-like ntuples in order to use it in the workshop lessons.
  
Please @jmhogan, @slaurila, @asdru30 could you check, comment, add anything else we might need?  @jmhogan I guess you got something on your side as well, I haven't checked yet.

I am not really sure what is the best way to put all this together.  I guess the civilized way would be to make a dev branch, for instance, in the [official repository](https://github.com/cms-opendata-analyses/AOD2NanoAODOutreachTool), and make PRs to it (after each person implementing it has tested it of course).  In that way, we could also trigger [Kati's minikube workflow](https://github.com/cms-opendata-analyses/AOD2NanoAODOutreachTool/commit/b4c685dc98dd9ab9298a2c8f627dad4662f741af) for extra security. Maybe @emanueleusai could administer this new branch?  What do you guys think?

- Add *reference* **triggers**.  I guess this could be easily done adding the required additional reference trigger [here](https://github.com/cms-opendata-analyses/AOD2NanoAODOutreachTool/blob/master/src/AOD2NanoAOD.cc#L64).  The corresponding parts of the code [here](https://github.com/cms-opendata-analyses/AOD2NanoAODOutreachTool/blob/master/src/AOD2NanoAOD.cc#L260) and [here](https://github.com/cms-opendata-analyses/AOD2NanoAODOutreachTool/blob/master/src/AOD2NanoAOD.cc#L386) will pick it up automatically I presume.  @slaurila what trigger do you think we should add?
- **PileUp** Info: After checking with @asdru30, it seems that in order to add the pileup information one needs to add the modifications he already implemented and tested in [his own version](https://github.com/asdru30/AOD2NanoAODOutreachTool) of the tool.  In particular:
    - The [header](https://github.com/asdru30/AOD2NanoAODOutreachTool/blob/18dd4357abf126137566215bf32e01f85248b763/src/AOD2NanoAOD.cc#L64)
    - The added [variables](https://github.com/asdru30/AOD2NanoAODOutreachTool/blob/18dd4357abf126137566215bf32e01f85248b763/src/AOD2NanoAOD.cc#L239)
    - [Branch](https://github.com/asdru30/AOD2NanoAODOutreachTool/blob/18dd4357abf126137566215bf32e01f85248b763/src/AOD2NanoAOD.cc#L368) booking
    - Info [extration](https://github.com/asdru30/AOD2NanoAODOutreachTool/blob/18dd4357abf126137566215bf32e01f85248b763/src/AOD2NanoAOD.cc#L653) for the in-time distribution and the true mean.

    @slaurila, is this all what is needed?  I have quickly re-tested it and it seems to work fine; at least according to [this exercise](https://twiki.cern.ch/twiki/bin/view/CMS/SWGuideCMSDataAnalysisSchool2014PileupReweighting#Getting_Started).  We could add extra info as well, if needed.  The vertex distribution was originally in place (it does not have any cuts, of course).

**Comment by slaurila** [comment]
Hi! About trigger efficiency measurement: I checked what was done in the original analysis. Based on AN2013_178_v8 (http://cms.cern.ch/iCMS/jsp/openfile.jsp?tp=draft&files=AN2013_178_v8.pdf), the efficiency measurement was done in two parts
1) for the tau leg, they used a single-muon trigger as a reference trigger; there is already some single-muon trigger included in the NanoAOD right?
2) for the muon leg, they did tag-and-probe; for this we would need to include the trigger-level muons in NanoAOD (needed for deltaR matching between trigger-level muons and offline muons), but no reference trigger is needed.

If we want to follow this approach somehow, we could either do both, or we could do only (1) and simply forget about the muon leg, or we could do (1) in the workshop and explain the idea of tag-and-probe but then just extract the final trigger SF from the AN plots and apply them - although the plots there are derived inclusively for full 2012ABCD so they aren't fully correct for the subset we have as open data I guess.

Another approach would be to pick a different approach, e.g. try to measure both legs simultaneously with a cross trigger - @jmhogan do I remember correctly that you suggested a single-electron trigger for this?

**Comment by slaurila** [comment]
About pileup: yes indeed the implementation by @asdru30 looks good, and consistent with the CMSDAS page, and I think it is everything we need. In fact, maybe these ancient Run-1 era CMSDAS pages could provide a bunch of other useful examples for Open Data purposes - never thought of that before! :)

**Comment by caredg** [comment]
Thanks @slaurila! Right, so these are the triggers already included: "HLT_IsoMu24_eta2p1",  "HLT_IsoMu24", "HLT_IsoMu17_eta2p1_LooseIsoPFTau20".
I would probably like to do 1 and 2 separately.  1 for sure, and if someone manages to implement 2 in time, well, that would be great!

**Comment by caredg** [comment]
> About pileup: yes indeed the implementation by @asdru30 looks good, and consistent with the CMSDAS page, and I think it is everything we need. In fact, maybe these ancient Run-1 era CMSDAS pages could provide a bunch of other useful examples for Open Data purposes - never thought of that before! :)

Ok, great!

**Comment by emanueleusai** [comment]
Hi @caredg , yes I can administer the new branch
