### ISSUE TITLE
Bash and git instructions for Windows users on the main page

### ISSUE THREAD

**Issue by katilp** [cms-opendata-workshop/2020-09-30-cms-open-data-workshop-for-theorists#18]
On the main page https://cms-opendata-workshop.github.io/2020-09-30-cms-open-data-workshop-for-theorists/ under Setup there's a set of tutorial instructions for Windows users for bash and git.

I'm not sure if it is useful in this way, i.e. adding additional bash for windows. The bash tutorial could be done in the CMS open data environment (or on WSL linux installation, or on docker on browser from @clelange and @alintulu ), for most efficient use of participants' time. 

We could possibly work to modify that with @Mmintyyy. @caredg @mattbellis Do you agree?

**Comment by caredg** [comment]
Hi @katilp.  Right, this is the default setup that comes with carpentry.  I did not even look at it.  I left it just in case is useful.  Certainly, that can be modified or removed.  I completely agree.

**Comment by katilp** [comment]
OK, I'll have a look once the other pre-exercises are there. Probably small changes will improve the first impression. Did we agree when the pre-exercises should be out? One week before?

**Comment by katilp** [comment]
@caredg Having a look again: as the carpentry lessons are linked as optional pre-exercises on unix,  git and python, we should remove the additional information after title "Setup", it is redundant and may be confusing.

**Comment by caredg** [comment]
Ok, I'll wipe out the setup section in the next push
