### ISSUE TITLE
Pre-exercises: Overview of presumed working mode

### ISSUE THREAD

**Issue by katilp** [cms-opendata-workshop/2020-09-30-cms-open-data-workshop-for-theorists#19]
@caredg @mattbellis In order to avoid a load of questions concerning whether to choose VM or docker, I would like to provide an overview of the working mode that we presume.

If you agree, this could be a separate page linked the tutorial schedule (a sort of foreword for the pre-exercises) and could go something like this (I will expand on this - or reduce it -  later, but this is just to give you an idea of what I have in mind and to get your first feedback, is it useful or not?):

Analysis of CMS data is most commonly done in two steps
   - **first**, selecting the data of interest and writing it to a new, smaller format
   - **second**, analysing the selected data.

The **first** step will be done using the CMS software (CMSSW) and in a computing environment compatible with the open data. For the computing environment, you can either
  - download a virtual machine (VM) image and run it on your computer. 
  - download a docker container.

Setting up the environment is the first pre-exercise. The choice between these two options depends on your own setup and your goals. We give a list a features which you can take into consideration when choosing between these two options at the end of this page. Learning some basics of CMSSW is the second pre-exercise. The code and commands to run are the same in VM and in docker. 

In the **second** step, during this workshop, we will use `root` data analysis framework. This is because
- the format of the output files from the first step is in root format
- the facilitators are familiar with root
- root is already installed in the CMS open data computing environment.

Learning some basics of root useful for this workshop is the third pre-exercise. Note that if you do not wish to use root, you can use the analysis tools of your choice afterwards, but  we will not be able to cover different options during this short workshop.
This second, analysis step can be done in the CMS open data virtual environment (whether VM or docker) or by passing the output files to you local setup and analysing them there. If you are familiar with root and have it installed on your local system, you may prefer doing it there. In this case, note that root version ... is used in the analysis example.

Here we list some features which may help you in choosing between the computing environments.

VM:
  - is quick to start, and only requires installation of a hypervisor program on your computer.
  - opens root GUI without problems in all OS (including Windows)
  - can be cumbersome to use (slow response)
  - is good to get a first touch with CMS open data or small-scale analysis, but is not practical when analysing large amounts of data.

Docker:
 - is more convenient for those used to the linux environment
 - requires installation of docker on your local system
 - opening root GUI in the docker container running on Windows requires quite some work (works fine on other systems, Mac?)
 - scales better for large-scale analysis

In addition, if neither of these solutions work for you, we plan to have a temporary tutorial setup running on browser during the workshop. Mind that this setup will not be available after the workshop.

**Comment by caredg** [comment]
Yes, I like it.. I will make a separate "lesson".  Should we call it workshop-lesson-orientation?

**Comment by mattbellis** [comment]
Only seeing this now but I really like this.

**Comment by katilp** [comment]
@caredg Let me know if you like me to prepare this page. And if yes, where in this repository?

**Comment by caredg** [comment]
Hi @katilp, yes it will be great if you can prepare it.  Actually lessons go outside the main repository of the workshop (so we can reuse them later in other workshops if needed; I guess that is the idea).  I will prepare right now the skeleton of the lesson and will let you know where to find it....

**Comment by caredg** [comment]
@kati, ok, the repository is [here](https://github.com/cms-opendata-workshop/workshop-lesson-orientation).  It is already setup.  For the front page, the files to modify are essentially the `_config.yml`, `index.md`, `setup.md` (although here is a better description of the [structure](https://carpentries.github.io/lesson-example/03-organization/index.html)) and then the epidodes go in `_episodes` directory and they need to bear numbers at the beginning, like `_episodes/01-introduction.md` ([here](https://carpentries.github.io/lesson-example/04-formatting/index.html) are more details if needed)

**Comment by katilp** [comment]
OK, thanks! It will be on one page to start with but I guess that's fine.

**Comment by katilp** [comment]
@caredg  The full repository is too much, it would need a lot of hacking to reduce it in one page. Is it easily possible to just add one page in the [schedule](https://cms-opendata-workshop.github.io/2020-09-30-cms-open-data-workshop-for-theorists/#schedule) without a full lesson, in a similar way as it is done for the slides eventually?

Update: Never mind, I'll find my way through. Should be done in an hour or two.

**Comment by caredg** [comment]
Ok.  Yes I can create one.  So, to make sure, it will be something like [this](https://cms-opendata-workshop.github.io/2020-09-30-cms-open-data-workshop-for-theorists/LICENSE.html), right, so if you click in an "orientation" or whatever button you get that page with the info above, right?

**Comment by katilp** [comment]
OK 😃 If it can be one page, that's great! Thanks!
