### ISSUE TITLE
Pre-exercise on docker

### ISSUE THREAD

**Issue by mattbellis** [cms-opendata-workshop/2020-09-30-cms-open-data-workshop-for-theorists#2]
Put together a pre-exercise on using docker, as it pertains to the open data and the workshop. 
This relates to cernopendata/cms-opendata-guide#27

**Comment by caredg** [comment]
@mattbellis, as you mentioned, it would be nice to test if the [brilcalc](http://opendata.cern.ch/docs/cms-guide-luminosity-calculation) instructions work.  This should also be considered for whomever work on #15 with virtual machines.  
Also, if time allows for a test, the [wsl2](http://opendata.cern.ch/docs/cms-guide-docker#running-cms-open-data-containers-on-wsl2) advice from Kati should be considered.

**Comment by caredg** [comment]
I was thinking that the docker pre-exercise lesson must have an episode on how to locally install the cvmfs client (i.e., in the host machine) or in the container itself.  Acess to cvmfs is a must and while this is already included in the VMs, it is less obvious how to access it in the container.

**Comment by mattbellis** [comment]
Sure thing. BTW, my docker for cmssw_5_3_32 is not opening and I've been trying to debug it. I just did a new download last night but still having issues. You?

**Comment by caredg** [comment]
> Sure thing. BTW, my docker for cmssw_5_3_32 is not opening and I've been trying to debug it. I just did a new download last night but still having issues. You?

I have a few docker containers that work well, so I am happy to help.  Based on 5_3_32 image I have two, one that uses cvmfs from the host and one in which the cvmfs client is installed directly in the container.  Both are working fine.  I also have a working  4_2_8-based one, but I guess we are not using that one for the workshop.

**Comment by caredg** [comment]
Done.  Issues moved [here](https://github.com/cms-opendata-workshop/workshop-lesson-docker-preexercises/issues).  Closes #10, which was repeated
